global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter_app'
    static_configs:
      - targets: ['node_exporter_app:9100']
      
  - job_name: 'node_exporter_db'
    static_configs:
      - targets: ['node_exporter_db:9100']
  - job_name: 'node_exporter_proxy'
    static_configs:
      - targets: ['node_exporter_proxy:9100']
  - job_name: 'node_exporter_prometheus'
    static_configs:
      - targets: ['node_exporter_prometheus:9100']
      
  